<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ApiError } from '../../api/documents'
import { createRetrievalCase, deleteRetrievalCase, inspectRetrieval, listRetrievalCases, listRetrievalRuns, runRetrievalCases } from '../../api/retrievalLab'
import { listKnowledgeBases } from '../../api/knowledgeBases'
import type { RetrievalCase, RetrievalInspect, RetrievalRun } from '../../types/retrievalLab'
import type { KnowledgeBaseRecord } from '../../types/knowledgeBases'
import RetrievalStages from './RetrievalStages.vue'

const question=ref('');const name=ref('');const expectedDocs=ref('');const expectedKeywords=ref('');const expectedNoAnswer=ref(false);const knowledgeBaseId=ref('');const bases=ref<KnowledgeBaseRecord[]>([]);const inspection=ref<RetrievalInspect|null>(null);const cases=ref<RetrievalCase[]>([]);const runs=ref<RetrievalRun[]>([]);const busy=ref(false);const error=ref('')
async function load(){try{const [kb,c,r]=await Promise.all([listKnowledgeBases(),listRetrievalCases(),listRetrievalRuns()]);bases.value=kb.items;cases.value=c;runs.value=r}catch(reason){error.value=reason instanceof ApiError?reason.message:'读取检索实验室失败'}}
async function inspect(){if(!question.value.trim())return;busy.value=true;error.value='';try{inspection.value=await inspectRetrieval(question.value.trim(),knowledgeBaseId.value)}catch(reason){error.value=reason instanceof ApiError?reason.message:'诊断失败'}finally{busy.value=false}}
async function save(){if(!name.value.trim()||!question.value.trim())return;try{await createRetrievalCase({name:name.value.trim(),question:question.value.trim(),knowledge_base_id:knowledgeBaseId.value||null,expected_document_ids:expectedDocs.value.split(',').map(x=>x.trim()).filter(Boolean),expected_keywords:expectedKeywords.value.split(',').map(x=>x.trim()).filter(Boolean),expected_no_answer:expectedNoAnswer.value});name.value='';await load()}catch(reason){error.value=reason instanceof ApiError?reason.message:'保存失败'}}
async function remove(id:string){if(!window.confirm('删除这条标准问题吗？'))return;await deleteRetrievalCase(id);await load()}
async function run(){busy.value=true;error.value='';try{await runRetrievalCases();await load()}catch(reason){error.value=reason instanceof ApiError?reason.message:'评测失败'}finally{busy.value=false}}
onMounted(load)
</script>
<template><main class="app-shell lab-shell"><header class="hero"><p class="eyebrow">RETRIEVAL LAB</p><h1>检索实验室</h1><p>观察问题如何经过关键词、语义、融合与精排，并用标准问题持续衡量调整效果。</p></header><section class="search-panel"><div class="lab-query"><label>测试问题<textarea v-model="question" placeholder="输入一个真实的公司资料问题"></textarea></label><label>知识库<select v-model="knowledgeBaseId"><option value="">全部知识库</option><option v-for="item in bases" :value="item.id">{{item.name}}</option></select></label><button :disabled="busy||!question.trim()" @click="inspect">{{busy?'分析中…':'分析检索过程'}}</button></div><p v-if="error" class="error">{{error}}</p></section><section v-if="inspection" class="results-panel"><h2>本次检索过程</h2><RetrievalStages :diagnostics="inspection.diagnostics"/><div class="admin-table-wrap" style="margin-top:14px"><table class="admin-table"><thead><tr><th>文档</th><th>片段</th><th>原始分数</th><th>反馈调整</th><th>最终分数</th></tr></thead><tbody><tr v-for="item in inspection.items" :key="item.chunk_id"><td>{{item.document_name}}</td><td>{{item.sequence_number}}</td><td>{{(item.base_score ?? item.final_score).toFixed(4)}}</td><td>{{(item.feedback_boost ?? 0).toFixed(4)}}</td><td>{{item.final_score.toFixed(4)}}</td></tr></tbody></table></div></section><section class="results-panel"><div class="section-heading"><div><p class="eyebrow">EVALUATION</p><h2>标准问题集 <span>{{cases.length}}</span></h2></div><button class="primary-action lab-run" :disabled="busy||!cases.length" @click="run">运行全部评测</button></div><div class="case-form"><input v-model="name" placeholder="用例名称"><input v-model="expectedDocs" placeholder="预期文档 UUID，逗号分隔"><input v-model="expectedKeywords" placeholder="预期关键词，逗号分隔"><label><input v-model="expectedNoAnswer" type="checkbox"> 应当无答案</label><button @click="save">保存当前问题为用例</button></div><ul class="governance-list"><li v-for="item in cases" :key="item.id"><div><strong>{{item.name}}</strong><small>{{item.question}} · {{item.expected_no_answer?'应无答案':'应有答案'}}</small></div><button class="text-danger" @click="remove(item.id)">删除</button></li></ul></section><section v-if="runs.length" class="results-panel"><h2>最近评测</h2><div class="metric-grid"><article><span>Recall@K</span><b>{{Math.round(runs[0].metrics.recall_at_k*100)}}%</b></article><article><span>MRR</span><b>{{runs[0].metrics.mrr}}</b></article><article><span>无答案准确率</span><b>{{Math.round(runs[0].metrics.no_answer_accuracy*100)}}%</b></article><article><span>平均耗时</span><b>{{runs[0].metrics.average_latency_ms}} ms</b></article></div></section></main></template>
