<script setup lang="ts">
import{onMounted,onUnmounted,ref}from'vue';import{cancelBatch,getBatch,ignoreBatchFile,retryBatchFile,uploadBatchFile}from'../../api/batches';import type{BatchDetail}from'../../types/batches'
const props=defineProps<{id:string}>();const emit=defineEmits<{close:[];changed:[]}>();const batch=ref<BatchDetail|null>(null);const filter=ref('');const error=ref('');let timer:number|undefined
async function refresh(){try{batch.value=await getBatch(props.id);if(['COMPLETED','CANCELLED'].includes(batch.value.status)&&timer){clearInterval(timer);timer=undefined}}catch(e){error.value=e instanceof Error?e.message:'读取失败'}}
async function retry(id:string){await retryBatchFile(props.id,id);await refresh();emit('changed')}
async function retryAll(){if(!batch.value)return;for(const file of batch.value.files.filter(x=>x.processing_status==='FAILED'||x.upload_status==='FAILED'))await retryBatchFile(props.id,file.id);await refresh();emit('changed')}
async function ignore(id:string){await ignoreBatchFile(props.id,id);await refresh();emit('changed')}
async function cancel(){if(confirm('确定取消这个导入批次吗？已经上传的资料不会被删除。')){await cancelBatch(props.id);await refresh();emit('changed')}}
async function resume(event:Event){const input=event.target as HTMLInputElement;const selected=Array.from(input.files||[]);if(!batch.value)return;const unresolved=new Set(batch.value.files.filter(x=>x.upload_status==='PENDING'||x.upload_status==='FAILED').map(x=>x.relative_path));for(const file of selected){const path=file.webkitRelativePath||file.name;if(unresolved.has(path))await uploadBatchFile(props.id,file,path,()=>{})}input.value='';await refresh();emit('changed')}
const visible=()=>batch.value?.files.filter(x=>!filter.value||x.upload_status===filter.value||x.processing_status===filter.value)||[]
onMounted(()=>{refresh();timer=window.setInterval(refresh,2500)});onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="detail-backdrop" @click.self="$emit('close')"><aside class="detail-panel batch-detail" v-if="batch"><header><div><p class="eyebrow">IMPORT BATCH</p><h2>{{batch.name}}</h2></div><button class="close-button" @click="$emit('close')">×</button></header><div class="batch-metrics"><div><b>{{batch.total_count}}</b><span>总文件</span></div><div><b>{{batch.indexed_count}}</b><span>可检索</span></div><div><b>{{batch.processing_count}}</b><span>处理中</span></div><div><b>{{batch.failed_count}}</b><span>失败</span></div></div><div class="batch-toolbar"><label class="secondary-action">继续上传<input class="visually-hidden" type="file" multiple webkitdirectory @change="resume"></label><button v-if="batch.failed_count" @click="retryAll">重试全部失败项</button><select v-model="filter"><option value="">全部状态</option><option value="FAILED">失败</option><option value="INDEXED">可检索</option><option value="PROCESSING">处理中</option><option value="PENDING">待上传</option></select><button @click="cancel">取消批次</button></div><p v-if="error" class="error">{{error}}</p><div class="batch-file-list"><article v-for="file in visible()" :key="file.id"><div><b>{{file.original_name}}</b><small>{{file.relative_path}}</small><em>{{file.upload_status}} · {{file.processing_status}}</em><p v-if="file.error_message">{{file.error_message}}</p></div><span><button v-if="file.processing_status==='FAILED'||file.upload_status==='FAILED'" @click="retry(file.id)">重试</button><button v-if="file.processing_status==='FAILED'" @click="ignore(file.id)">忽略</button></span></article></div></aside></div></template>
